"""
Evaluates the scan-rescan variability of the spinal cord (SC) segmentation volume in the PAM50 space,
for each pair generated by `generate_study_files.py`.

The CSA per PAM50 slice is computed with:
    sct_process_segmentation -i <sc_seg> -anat <image> -perslice 1 -discfile <discs> -normalize-PAM50 1
and the SC volume is the CSA summed over the PAM50 slices common to the two compared segmentations.

Two comparisons are made:
    - run-01 SC seg vs run-02 SC seg (each in its native space)
    - run-01 SC seg vs run-02 SC seg registered to run-01 (processed with the run-01 image and disc labels)

Outputs (in the output folder):
    - sc_seg_variability.csv: one line per pair (including the has_lesion field of the input json)
    - sc_volume_diff_percent.png: scatter plots of the SC volume percentage difference (native and
      registered side by side, same scales)

Arguments:
    -i / --input        Path to the output folder of generate_study_files.py
    -o / --output       Path to the output folder

Author: Pierre-Louis Benveniste
"""

import argparse
import json
import os
from pathlib import Path
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from tqdm import tqdm


def run(cmd):
    assert os.system(cmd) == 0, f"Command failed: {cmd}"


def csa_pam50(sc_seg, image, discs, qc_dir):
    """Returns the CSA per PAM50 slice of a SC segmentation."""
    csv = Path(str(sc_seg).replace(".nii.gz", "_csa-PAM50.csv"))
    if not csv.exists():
        run(f"sct_process_segmentation -i {sc_seg} -anat {image} -perslice 1 -discfile {discs} -normalize-PAM50 1 -qc {qc_dir} -o {csv}")
    return pd.read_csv(csv).dropna(subset=["MEAN(area)"]).set_index("Slice (I->S)")["MEAN(area)"]


def compare_volumes(csa_1, csa_2, prefix):
    """Compares the SC volumes of two segmentations over their common PAM50 slices."""
    common_slices = csa_1.index.intersection(csa_2.index)
    vol_1 = csa_1.loc[common_slices].sum()
    vol_2 = csa_2.loc[common_slices].sum()
    return {
        f"{prefix}_first_PAM50_slice": common_slices.min(),
        f"{prefix}_last_PAM50_slice": common_slices.max(),
        f"{prefix}_sc_volume_run-01_mm3": vol_1,
        f"{prefix}_sc_volume_run-02_mm3": vol_2,
        f"{prefix}_sc_volume_diff_mm3": vol_2 - vol_1,
        f"{prefix}_sc_volume_abs_diff_percent": abs(vol_2 - vol_1) / ((vol_1 + vol_2) / 2) * 100,
    }


def process_pair(pair, dataset, study_dir):
    qc_dir = study_dir / "qc"
    img_1, img_2 = dataset / pair["scan_run-01"], dataset / pair["rescan_run-02"]
    seg_1, seg_2 = study_dir / pair["sc_seg_run-01"], study_dir / pair["sc_seg_run-02"]
    discs_1, discs_2 = study_dir / pair["disc_labels_run-01"], study_dir / pair["disc_labels_run-02"]

    # Register the run-02 SC seg to run-01
    seg_2_reg = Path(str(seg_2).replace(".nii.gz", "_space-run01.nii.gz"))
    if not seg_2_reg.exists():
        run(f"sct_apply_transfo -i {seg_2} -d {img_1} -w {study_dir / pair['warp_run-02_to_run-01']} -x nn -o {seg_2_reg}")

    csa_1 = csa_pam50(seg_1, img_1, discs_1, qc_dir)
    csa_2 = csa_pam50(seg_2, img_2, discs_2, qc_dir)
    csa_2_reg = csa_pam50(seg_2_reg, img_1, discs_1, qc_dir)

    return {
        "subject": pair["subject"],
        "session": pair["session"],
        "acquisition": pair["acquisition"],
        "has_lesion": pair["has_lesion"],
        **compare_volumes(csa_1, csa_2, "native"),
        **compare_volumes(csa_1, csa_2_reg, "registered"),
    }


def main():
    parser = argparse.ArgumentParser(description="Evaluate the scan-rescan variability of the SC segmentation volume in the PAM50 space.")
    parser.add_argument("-i", "--input", required=True, type=Path, help="Path to the output folder of generate_study_files.py")
    parser.add_argument("-o", "--output", required=True, type=Path, help="Path to the output folder")
    args = parser.parse_args()

    # Build output folder if it does not exist
    args.output.mkdir(parents=True, exist_ok=True)

    study_dir = args.input.resolve()
    with open(study_dir / "study_files.json") as f:
        study = json.load(f)

    results = []
    for pair in tqdm([p for p in study["pairs"] if p["status"] == "success"]):
        try:
            results.append(process_pair(pair, Path(study["dataset"]), study_dir))
        except Exception as e:
            print(f"Failed for {pair['subject']}/{pair['session']}/acq-{pair['acquisition']}: {e}")

    df = pd.DataFrame(results)
    df.to_csv(args.output / "sc_seg_variability.csv", index=False)
    print(f"Results of {len(results)} pairs saved to {args.output}")

    # Scatter plot of the SC volume percentage difference (native and registered)
    fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharex=True, sharey=True)
    for ax, prefix in zip(axes, ("native", "registered")):
        sns.scatterplot(x=(df[f"{prefix}_sc_volume_run-01_mm3"] + df[f"{prefix}_sc_volume_run-02_mm3"]) / 2,
                        y=df[f"{prefix}_sc_volume_abs_diff_percent"], hue=df["acquisition"], ax=ax)
        ax.set(title=f"SC volume difference in PAM50 ({prefix})", xlabel="Mean SC volume", ylabel="Absolute volume difference (%)")
        ax.yaxis.grid(True, linestyle="--", alpha=0.3)
        ax.set_axisbelow(True)
    fig.tight_layout()
    fig.savefig(args.output / "sc_volume_diff_percent.png", dpi=200)
    plt.close(fig)


if __name__ == "__main__":
    main()
